export const userOutlayTags: TagItem[] = [
  { title: '餐饮', value: 'catering' },
  { title: '外卖', value: 'takeaway' },
  { title: '零食', value: 'snack' },
  { title: '小吃', value: 'refreshments' },
  { title: '酒水', value: 'drink' },
  { title: '购物', value: 'shopping' },
  { title: '日用品', value: 'commodity' },
  { title: '衣服', value: 'clothes' },
  { title: '数码', value: 'digital' },
  { title: '电器', value: 'electricalAppliances' },
  { title: '家居', value: 'home' },
  { title: '化妆品', value: 'cosmetic' },
  { title: '果蔬', value: 'fruits' },
  { title: '娱乐', value: 'entertainment' },
  { title: '游戏', value: 'game' },
  { title: '电影', value: 'movie' },
  { title: '交通', value: 'transportation' },
  { title: '公交', value: 'bus' },
  { title: '地铁', value: 'subway' },
  { title: '火车', value: 'train' },
  { title: '飞机', value: 'plane' },
  { title: '话费网费', value: 'call' },
  { title: '水电费', value: 'water' },
  { title: '医疗', value: 'medicine' },

]

export const userIncomeTags: TagItem[] = [
  { title: '理财', value: 'moneyManagement' },
  { title: '工资', value: 'salary' },
  { title: '兼职', value: 'partTimeJob' },
  { title: '奖金', value: 'bonus' },
  { title: '报销', value: 'refund' },
  { title: '礼金', value: 'giftCash' },
]